services:
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: klickr
      POSTGRES_USER: klickr
      POSTGRES_PASSWORD: klickr
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
  worker:
    build: .
    command: ["./worker.sh"]
    environment:
      REDIS_URL: redis://redis
    volumes:
      - ./data/klickr:/app/klickr/static
    depends_on:
      - redis
  klickr:
    build: .
    ports:
     - "5005:5000"
    environment:
      DATABASE_URL: postgres://klickr:klickr@db/klickr
      REDIS_URL: redis://redis
    volumes:
      - ./data/klickr:/app/klickr/static
    depends_on:
      - db
      - redis
